"""Helpers for generated auto-approval extensions."""

from __future__ import annotations

import re
from pathlib import Path

from taui.extensions import ExtensionRegistry

AUTO_APPROVE_MARKER = "# Auto-generated by Taui: auto-approve tool extension"


def auto_approve_extension_path(
    tool_name: str,
    working_dir: Path,
    scope: str,
) -> Path:
    """Return the extension path for a generated tool auto-approval extension."""
    safe_name = re.sub(r"[^a-zA-Z0-9_]+", "_", tool_name).strip("_") or "tool"
    if scope == "project":
        base = working_dir / ExtensionRegistry.PROJECT_DIR
    elif scope == "global":
        base = ExtensionRegistry.GLOBAL_DIR
    else:
        raise ValueError(f"Unknown extension scope: {scope!r}")
    return base / f"taui_auto_approve_{safe_name}.py"


def render_auto_approve_extension(tool_name: str) -> str:
    """Render an extension that replaces a tool and marks it auto-approved."""
    return f'''{AUTO_APPROVE_MARKER}
"""Auto-approve the {tool_name} tool."""

from __future__ import annotations

from taui.tools.executor import PolicyDecision

TOOL_NAME = {tool_name!r}


class AutoApprovedTool:
    """Delegate to the original tool while policy marks it as auto-approved."""

    def __init__(self, inner):
        self._inner = inner

    @property
    def name(self):
        return self._inner.name

    @property
    def description(self):
        return self._inner.description

    @property
    def schema(self):
        return self._inner.schema

    @property
    def category(self):
        return self._inner.category

    @property
    def guidelines(self):
        return getattr(self._inner, "guidelines", "")

    @property
    def working_dir(self):
        return getattr(self._inner, "working_dir", None)

    @working_dir.setter
    def working_dir(self, value):
        if hasattr(self._inner, "working_dir"):
            self._inner.working_dir = value

    async def execute(self, arguments):
        return await self._inner.execute(arguments)

    def __getattr__(self, name):
        return getattr(self._inner, name)


def register(ctx):
    if ctx.tools is None:
        return
    original = ctx.tools.get(TOOL_NAME)
    ctx.tools.register_or_replace(AutoApprovedTool(original))
    if getattr(ctx, "policy", None) is not None:
        ctx.policy.set(TOOL_NAME, PolicyDecision.AUTO)
'''


def write_auto_approve_extension(
    tool_name: str,
    working_dir: Path,
    scope: str = "project",
) -> Path:
    """Create or replace the generated extension file for a tool."""
    path = auto_approve_extension_path(tool_name, working_dir, scope)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_auto_approve_extension(tool_name), encoding="utf-8")
    return path
